export const PUBLISH = 'PUBLISH'
export const SAVE_DRAFT = 'SAVE_DRAFT'
export const CANCEL_RELEASE = 'CANCEL_RELEASE'
export const DIALOG_STATUS = 'DIALOG_STATUS'
export const SAVE_ARTICLE = 'SAVE_ARTICLE'

export const SWITCH_MENU = 'SWITCH_MENU'

// 用户信息

export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'
