export const PUBLISH = 'PUBLISH'
export const SAVE_DRAFT = 'SAVE_DRAFT'
export const CANCEL_RELEASE = 'CANCEL_RELEASE'
export const DIALOG_STATUS = 'DIALOG_STATUS'
export const SAVE_ARTICLE = 'SAVE_ARTICLE'

export const SWITCH_MENU = 'SWITCH_MENU'

// 用户信息
export const FETCH_PROFILE = 'FETCH_PROFILE'
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL'

// 媒体用户信息
export const FETCH_MEDIA = 'FETCH_MEDIA'
export const FETCH_MEDIA_FAIL = 'FETCH_MEDIA_FAIL'

// 通知
export const FETCH_NOTIFICATION = 'FETCH_NOTIFICATION'
export const FETCH_NOTIFICATION_FAIL = 'FETCH_NOTIFICATION_FAIL'
