export const category = [{
    type: 'news',
    name: '新闻'
}, {
    type: 'news_society',
    name: '社会'
}, {
    type: 'news_entertainment',
    name: '娱乐'
}, {
    type: 'movie',
    name: '电影'
}, {
    type: 'news_tech',
    name: '科技'
}, {
    type: 'digital',
    name: '数码'
}, {
    type: 'news_car',
    name: '汽车'
}, {
    type: 'news_sports',
    name: '体育'
}, {
    type: 'news_finance',
    name: '财经'
}, {
    type: 'news_military',
    name: '军事'
}, {
    type: 'news_world',
    name: '国际'
}, {
    type: 'news_fashion',
    name: '时尚'
}, {
    type: 'marvel',
    name: '奇葩'
}, {
    type: 'news_game',
    name: '游戏'
}, {
    type: 'news_travel',
    name: '旅游'
}, {
    type: 'news_baby',
    name: '育儿'
}, {
    type: 'fitness',
    name: '瘦身'
}, {
    type: 'news_regimen',
    name: '养生'
}, {
    type: 'news_food',
    name: '美食'
}, {
    type: 'news_history',
    name: '历史'
}, {
    type: 'news_discovery',
    name: '探索'
}, {
    type: 'news_story',
    name: '故事'
}, {
    type: 'news_essay',
    name: '美文'
}, {
    type: 'emotion',
    name: '情感'
}, {
    type: 'news_health',
    name: '健康'
}, {
    type: 'news_edu',
    name: '教育'
}, {
    type: 'news_home',
    name: '家居'
}, {
    type: 'news_house',
    name: '房产'
}, {
    type: 'funny',
    name: '搞笑'
}, {
    type: 'news_astrology',
    name: '星座'
}, {
    type: 'news_culture',
    name: '文化'
}, {
    type: 'news_pet',
    name: '宠物'
}, {
    type: 'news_law',
    name: '法制'
}, {
    type: 'news_career',
    name: '职场'
}, {
    type: 'comic',
    name: '漫画'
}, {
    type: 'news_comic',
    name: '动漫'
}, {
    type: 'science_all',
    name: '科学'
}, {
    type: 'news_design',
    name: '设计'
}, {
    type: 'news_photography',
    name: '摄影'
}, {
    type: 'news_collect',
    name: '收藏'
}, {
    type: 'news_agriculture',
    name: '三农'
}, {
    type: 'news_psychology',
    name: '心理'
}]
